# action.yml
name: Upload File
inputs:
  sha:
    required: true
  key:
    required: true

runs:
  using: "composite"
  steps:

    - name: Create checksum file
      shell: bash
      run: |
        echo "${{ inputs.sha }}" > "${{ github.sha }}-${{ inputs.key }}.txt"

    - name: Upload checksum file
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
      with:
        name: ${{ github.sha }}-${{ inputs.key }}.txt
        path: ${{ github.sha }}-${{ inputs.key }}.txt
        retention-days: 5
