# action.yml
name: Checksum Validate Action
description: Generate and validate checksums
branding:
  icon: 'lock'
  color: 'orange'
inputs:
  validate:
    description: Check if checksums match
    default: false
  key:
    description: String to keep unique checksums separate
    required: true
  fail-invalid:
    description: Fail step if invalid checksum
    default: false
  input:
    description: String or command for checksum
    required: true
outputs:
  valid:
    description: True if checksums match
    value: ${{ steps.validate_checksum.outputs.valid }}

runs:
  using: "composite"
  steps:

    - name: Get input SHA
      id: input_sha
      shell: bash
      run: |
        #https://stackoverflow.com/a/35977842
        # Retries a command on failure.
        # $1 - the max number of attempts
        # $2... - the command to run

        retry() {
            local -r -i max_attempts="$1"; shift
            local -i attempt_num=1
            until "$@"
            do
                if ((attempt_num==max_attempts))
                then
                    echo "Attempt $attempt_num failed and there are no more attempts left!"
                    return 1
                else
                    echo "Attempt $attempt_num failed! Trying again in $attempt_num seconds..."
                    sleep $((attempt_num++))
                fi
            done
        }
        input_cmd="${{ inputs.input }}"
        sha="$(retry 5 echo "$input_cmd" | sha256sum)"
        echo "sha=$sha" >> $GITHUB_OUTPUT

    - name: Create checksum file
      if: inputs.validate != 'true'
      shell: bash
      run: |
        echo "${{ steps.input_sha.outputs.sha }}" > "${{ github.sha }}-${{ inputs.key }}.txt"

    - name: Upload checksum file
      if: inputs.validate != 'true'
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
      with:
        name: ${{ github.sha }}-${{ inputs.key }}.txt
        path: ${{ github.sha }}-${{ inputs.key }}.txt
        retention-days: 5

    - name: Download checksum file
      if: inputs.validate == 'true'
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
      with:
        name: ${{ github.sha }}-${{ inputs.key }}.txt

    - name: Validate pre and post checksums
      if: inputs.validate == 'true'
      id: validate_checksum
      shell: bash
      run: |
        echo "${{ steps.input_sha.outputs.sha }}" > "${{ github.sha }}-${{ inputs.key }}-2.txt"
        DIFF=$(diff -q "${{ github.sha }}-${{ inputs.key }}-2.txt" "${{ github.sha }}-${{ inputs.key }}.txt") || true
        codevalid=true
        if [ "$DIFF" != "" ]
        then
          codevalid=false
        fi
        echo "valid=$codevalid" >> $GITHUB_OUTPUT

    - name: Create summary
      if: inputs.validate == 'true'
      run: |
        # Use ternary operator to assign emoji based on validity
        emoji=${{ steps.validate_checksum.outputs.valid == 'true' && ':white_check_mark:' || ':x:' }}
        valid=${{ steps.validate_checksum.outputs.valid == 'true' && 'valid' || 'INVALID' }}
        echo "### $emoji ${{ inputs.key }} checksum $valid $emoji" >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Fail if invalid checksum
      if: inputs.validate == 'true' && steps.validate_checksum.outputs.valid != 'true' && inputs.fail-invalid == 'true'
      run: exit 1
      shell: bash
