# action.yml
name: Checksum Validate Action
description: Generate and validate checksums
branding:
  icon: 'lock'
  color: 'orange'
inputs:
  validate:
    description: Check if checksums match
    default: false
  key:
    description: String to keep unique checksums separate
    required: true
  fail-invalid:
    description: Fail step if invalid checksum
    default: false
  input:
    description: String or command for checksum
    required: true
outputs:
  valid:
    description: True if checksums match
    value: ${{ steps.validate_file.outputs.valid }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4.1.1
      with:
        repository: JosiahSiegel/checksum-validate-action

    - name: Get input SHA
      id: get_sha
      uses: ./.github/actions/checksum
      with:
        input: ${{ inputs.input }}

    - name: Upload checksum file
      if: inputs.validate != 'true'
      uses: ./.github/actions/upload-file
      with:
        sha: ${{ steps.get_sha.outputs.sha }}
        key: ${{ inputs.key }}

    - name: Validate checksum file
      if: inputs.validate == 'true'
      id: validate_file
      uses: ./.github/actions/validate-file
      with:
        sha: ${{ steps.get_sha.outputs.sha }}
        key: ${{ inputs.key }}

    - name: Fail if invalid checksum
      if: inputs.validate == 'true' && steps.validate_file.outputs.valid != 'true' && inputs.fail-invalid == 'true'
      run: exit 1
      shell: bash
