# action.yml
name: Validate File
inputs:
  sha:
    required: true
  key:
    required: true
outputs:
  valid:
    value: ${{ steps.validate_checksum.outputs.valid }}

runs:
  using: "composite"
  steps:

    - name: Download checksum file
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
      with:
        name: ${{ github.sha }}-${{ inputs.key }}.txt

    - name: Validate pre and post checksums
      id: validate_checksum
      shell: bash
      run: |
        echo "${{ inputs.sha }}" > "${{ github.sha }}-${{ inputs.key }}-2.txt"
        DIFF=$(diff -q "${{ github.sha }}-${{ inputs.key }}-2.txt" "${{ github.sha }}-${{ inputs.key }}.txt") || true
        codevalid=true
        if [ "$DIFF" != "" ]
        then
          codevalid=false
        fi
        echo "valid=$codevalid" >> $GITHUB_OUTPUT

    - name: Create summary
      run: |
        # Use ternary operator to assign emoji based on validity
        emoji=${{ steps.validate_checksum.outputs.valid == 'true' && '✅' || '❌' }}
        valid=${{ steps.validate_checksum.outputs.valid == 'true' && 'valid' || 'INVALID' }}
        echo "### $emoji ${{ inputs.key }} checksum $valid $emoji" >> $GITHUB_STEP_SUMMARY
      shell: bash
